name: jobs_15
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  path: ^1.8.3
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  card_swiper: ^3.0.1
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/app_frontend/default photo/company_img.svg
    - lib/app_frontend/default photo/profile_img.svg 