name: jobs_15
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^0.8.6
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.5
  file_picker: 10.1.9
  font_awesome_flutter: ^10.7.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  card_swiper: ^3.0.1
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  provider: ^6.1.5
  flutter_local_notifications: ^19.3.0
  maplibre_gl: ^0.22.0
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/app_frontend/default photo/company_img.svg
    - lib/app_frontend/default photo/profile_img.svg 