# Generated by Django 5.0.2 on 2025-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('work_category', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('OPS', 'Operations'), ('OTH', 'Other')], max_length=3)),
                ('has_work_experience', models.BooleanField(default=False)),
                ('currently_working', models.BooleanField(default=False)),
                ('education_level', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=3)),
                ('degree', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('physically_challenged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Registration',
                'verbose_name_plural': 'Employee Registrations',
                'db_table': 'employee_registration',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('candidate_type', models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
            },
        ),
    ]
