# Generated by Django 5.0.2 on 2025-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='work_category',
            field=models.CharField(max_length=100),
        ),
    ]
