# Generated by Django 5.0.2 on 2025-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_employeeregistration_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegistration',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('gst_number', models.CharField(max_length=30)),
                ('founder_name', models.CharField(max_length=100)),
                ('business_category', models.CharField(max_length=50)),
                ('year_of_establishment', models.CharField(max_length=4)),
                ('employee_range', models.CharField(max_length=20)),
                ('industry_sector', models.CharField(max_length=50)),
                ('disability_hiring', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employer Registration',
                'verbose_name_plural': 'Employer Registrations',
                'db_table': 'employer_registration',
            },
        ),
    ]
