# Generated by Django 5.0.2 on 2025-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_employerregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='education_level',
            field=models.CharField(choices=[('BELOW_8TH', 'Below 8th'), ('10TH', '10th'), ('12TH', '12th'), ('DIPLOMA', 'Diploma'), ('ITI', 'ITI'), ('UG', 'UG'), ('PG', 'PG')], max_length=10),
        ),
    ]
