# Generated by Django 5.0.2 on 2025-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_employeeregistration_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
