# Generated by Django 5.0.2 on 2025-06-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_employeeregistration_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='subscription_type',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='view_credits',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='ViewedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employeeregistration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employerregistration')),
            ],
            options={
                'verbose_name': 'Viewed Candidate',
                'verbose_name_plural': 'Viewed Candidates',
                'db_table': 'viewed_candidate',
                'unique_together': {('employer', 'employee')},
            },
        ),
    ]
