# Generated by Django 5.0.2 on 2025-06-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_employerregistration_subscription_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employerregistration')),
            ],
            options={
                'verbose_name': 'Company Certificate',
                'verbose_name_plural': 'Company Certificates',
                'db_table': 'company_certificate',
            },
        ),
    ]
