# Generated by Django 5.0.2 on 2025-06-12 15:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_companycertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('about', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('include', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('image_1', models.URLField(blank=True, max_length=500, null=True)),
                ('image_2', models.URLField(blank=True, max_length=500, null=True)),
                ('image_3', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employerregistration')),
            ],
            options={
                'verbose_name': 'Employer Feedback',
                'verbose_name_plural': 'Employer Feedbacks',
                'db_table': 'employer_feedback',
            },
        ),
    ]
