# Generated by Django 5.0.2 on 2025-06-16 07:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_employerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('duration', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('city', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('district', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(choices=[('BELOW_8TH', 'Below 8th'), ('10TH', '10th'), ('12TH', '12th'), ('DIPLOMA', 'Diploma'), ('ITI', 'ITI'), ('UG', 'UG'), ('PG', 'PG')], max_length=10)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('contact_number_1', models.CharField(max_length=15)),
                ('contact_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_landline', models.CharField(blank=True, max_length=20, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_video', models.FileField(blank=True, null=True, upload_to='job_videos/')),
                ('physically_challenged', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('special_benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('posted', 'Posted'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='apps.employerregistration')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'db_table': 'job_post',
            },
        ),
    ]
