# Generated by Django 5.0.2 on 2025-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_video',
            field=models.FileField(blank=True, null=True, upload_to='job_video/'),
        ),
    ]
