# Generated by Django 5.0.2 on 2025-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_jobpost_job_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_video',
            field=models.FileField(blank=True, null=True, upload_to='job_videos/'),
        ),
    ]
