# Generated by Django 5.0.2 on 2025-06-17 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_jobpost_job_video_url_alter_jobpost_job_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='district',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='special_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None),
        ),
    ]
