# Generated by Django 5.0.2 on 2025-06-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_jobpost_city_alter_jobpost_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employeeregistration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employerregistration')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.jobpost')),
            ],
            options={
                'verbose_name': 'Favorite Job',
                'verbose_name_plural': 'Favorite Jobs',
                'db_table': 'fav_jobs',
                'unique_together': {('employee', 'job', 'employer')},
            },
        ),
    ]
