# Generated by Django 5.0.2 on 2025-06-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_favjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employeeregistration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employerregistration')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.jobpost')),
            ],
            options={
                'verbose_name': 'Viewed Job',
                'verbose_name_plural': 'Viewed Jobs',
                'db_table': 'viewed_jobs',
                'unique_together': {('job_post', 'employer', 'employee')},
            },
        ),
    ]
