# Generated by Django 5.0.2 on 2025-06-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_viewedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others'), ('anyone', 'Anyone')], default='anyone', help_text='Preferred gender for the job', max_length=12),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('divorced', 'Divorced'), ('not_preferred', 'Not Preferred')], default='not_preferred', help_text='Preferred marital status for the job', max_length=15),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='max_age',
            field=models.PositiveIntegerField(default=80, help_text='Maximum age for the job'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_age',
            field=models.PositiveIntegerField(default=18, help_text='Minimum age for the job'),
        ),
    ]
