# Generated by Django 5.0.2 on 2025-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_jobpost_gender_jobpost_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedjob',
            name='applied',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
