# Generated by Django 5.0.2 on 2025-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_viewedjob_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='grade',
            field=models.IntegerField(default=1, help_text='Number of stars for employer ranking, editable only by superuser'),
        ),
    ]
