# Generated by Django 5.0.2 on 2025-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_employerregistration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='no_of_post',
            field=models.IntegerField(default=0),
        ),
    ]
