# Generated by Django 5.0.2 on 2025-07-07 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_employerregistration_no_of_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerfeedback',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
