# Generated by Django 5.2.4 on 2025-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_employerfeedback_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
