# Generated by Django 5.2.4 on 2025-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_employeeregistration_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
