# Generated by Django 5.2.4 on 2025-07-17 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_employeeregistration_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='subscription_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
