# Generated by Django 5.2.4 on 2025-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_employerregistration_subscription_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
