# Generated by Django 4.2.23 on 2025-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_employeeregistration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='taluk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
