# Generated by Django 4.2.23 on 2025-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_employerregistration_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('divorced', 'Divorced'), ('not_preferred', 'Not Preferred'), ('anyone', 'Anyone')], default='not_preferred', help_text='Preferred marital status for the job', max_length=15),
        ),
    ]
