# Generated by Django 4.2.23 on 2025-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_jobpost_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycertificate',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='employeeregistration',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='employerregistration',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_video_url',
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificate/'),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photo/'),
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_photo/'),
        ),
        migrations.AlterField(
            model_name='employerfeedback',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_image/'),
        ),
        migrations.AlterField(
            model_name='employerfeedback',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_image/'),
        ),
        migrations.AlterField(
            model_name='employerfeedback',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_image/'),
        ),
    ]
